spring:
  datasource:
    ##driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/bridge_sns?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: hobulian
    password: bridgeadmin
    mapper-locations: classpath:/mapper/**/*.xml

  test:
    database:
      replace: none
